[project]
name = 'bitlot-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.sip-010-trait-ft-standard]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = '2.5'

[contracts.bitlot-token]
path = 'contracts/bitlot-token.clar'
clarity_version = 2
epoch = '2.5'

[contracts.bitlot-v2]
path = 'contracts/bitlot.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
